### ISSUE TITLE
Sapper support

### ISSUE THREAD

**Issue by JHethDev** [silvestrevivo/svelte-typeform-embed#12]
Is there any way to get this working with Sapper? I tried and get the following error:
`'makePopup' is not exported by 'node_modules\@typeform\embed\build\lib.pure.js'`

**Comment by silvestrevivo** [comment]
@JHethDev If you install it as devDependency, it works. That happens sometimes with some packages to be installed in Sapper. I would like to avoid the use of replace in the rollup to make it working, but that is part of another issue #5 .
